//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForcastLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherForcastLib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03abf0d0b72e5c8b41d6b4dc9fcdd6c9.
        /// </summary>
        public static string appiKey {
            get {
                return ResourceManager.GetString("appiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:/temp.
        /// </summary>
        public static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.openweathermap.org/data/2.5/weather.
        /// </summary>
        public static string urlCurrent {
            get {
                return ResourceManager.GetString("urlCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode;Plaatsnaam;Deelgemeente;Provincie
        ///2970;&apos;S Gravenwezel;Ja;Antwerpen
        ///3700;&apos;S Herenelderen;Ja;Limburg
        ///7510;3 Suisses;;
        ///9420;Aaigem;Ja;Oost-Vlaanderen 
        ///8511;Aalbeke;Ja;West-Vlaanderen
        ///3800;Aalst;Ja;Limburg
        ///9300;AALST;Neen;Oost-Vlaanderen 
        ///9880;AALTER;Neen;Oost-Vlaanderen 
        ///3200;AARSCHOT;Neen;Vlaams-Brabant
        ///8700;Aarsele;Ja;West-Vlaanderen
        ///8211;Aartrijke;Ja;West-Vlaanderen
        ///2630;AARTSELAAR;Neen;Antwerpen
        ///4557;Abée;Ja;Luik
        ///4280;Abolens;Ja;Luik
        ///3930;Achel;Ja;Limburg
        ///5590;Achêne;Ja;Namen
        ///5362 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
